version: '3.1'
services:
  salaryDB:
    image: mariadb
    container_name: salaryDB
    restart: always
    environment:
      - MYSQL_DATABASE=salarydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  salary:
    depends_on:
      - salaryDB
    image: tomcat:8.5.61
    container_name: salary
    restart: always
    volumes:
      - ./Docker_configs/server.xml:/usr/local/tomcat/conf/server.xml
      - ./Docker_configs/context.xml:/usr/local/tomcat/conf/context.xml
      - ./target/salary.war:/usr/local/tomcat/webapps/salary.war
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=salarydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=